import { Layout } from '../../layouts/Shell.jsx'
import { deploymentChecklist, deploymentHistory, publishQueue } from '../../services/publishing.js'

const stages = ['Draft saved', 'Review requested', 'Owner approved', 'Published live']

export function PublishRequests({ client = false }) {
  const visibleRequests = client ? publishQueue.filter(row => row.website === 'TwoToneTaj') : publishQueue
  const selected = visibleRequests[0]
  return <Layout client={client} title="Publish Requests"><section className="moduleHero card"><div><span>{client ? 'Client Publishing' : 'Owner Review'}</span><h2>{client ? 'Request Website Updates' : 'Review & Publish Changes'}</h2><p>{client ? 'Save website edits, preview changes, then request KSJ Digital to publish them live.' : 'Review client changes, approve safe updates, and publish them to the correct website.'}</p></div><button>{client ? 'Request Publish' : 'Review Queue'}</button></section><div className="publishGrid"><section className="card publishPanel wide"><div className="panelHead"><h2>{client ? 'My Requests' : 'Client Requests'}</h2><button>{client ? 'New Request' : 'Approve Selected'}</button></div>{visibleRequests.map(row => <article className="publishRow" key={row.id}><div><b>{row.title}</b><small>{row.website} · Requested by {row.requester} · {row.updated}</small></div><span>{row.status}</span>{!client && <button>Review</button>}</article>)}</section><section className="card publishPanel"><div className="panelHead"><h2>Publish Safety</h2><button>Settings</button></div><div className="safetyList"><span>Clients cannot deploy directly.</span><span>Owner approval required before live publish.</span><span>Changes are mapped to safe content fields.</span><span>Website layout and code stay protected.</span></div></section></div><section className="publishReviewGrid"><div className="card publishPanel reviewDetail"><div className="panelHead"><h2>{client ? 'Request Details' : 'Review Details'}</h2><button>{client ? 'View Preview' : 'Approve'}</button></div><h3>{selected.title}</h3><p>{selected.target}</p><div className="changedFields">{selected.fields.map(field => <span key={field}>{field}</span>)}</div><div className="reviewActions"><button>Preview Changes</button>{!client && <button>Reject</button>}{!client && <button>Approve & Prepare Publish</button>}</div></div><div className="card publishPanel"><div className="panelHead"><h2>Deployment Checklist</h2><button>Run Checks</button></div>{deploymentChecklist.map((item, index) => <article className="checkItem" key={item[0]}><b>0{index + 1}</b><div><strong>{item[0]}</strong><small>{item[1]}</small></div><span>Ready</span></article>)}</div></section><section className="card publishPanel"><div className="panelHead"><h2>Publishing Workflow</h2><button>View History</button></div><div className="publishSteps ownerSteps">{stages.map((stage, index) => <span key={stage}><b>0{index + 1}</b>{stage}</span>)}</div></section><section className="card publishPanel historyPanel"><div className="panelHead"><h2>Recent Publishing History</h2><button>Open Log</button></div>{deploymentHistory.map(row => <article key={`${row[0]}-${row[1]}`}><div><b>{row[1]}</b><small>{row[0]} · {row[3]}</small></div><span>{row[2]}</span></article>)}</section></Layout>
}
