import { Layout } from '../../layouts/Shell.jsx'
import { websites } from '../../services/mockData.js'
import { WebsiteCard } from '../../components/WebsiteCard.jsx'

const filters = ['All', 'Live', 'Draft']
const platformStats = [['Websites','3','managed'],['Owners','3','assigned'],['Publishing','3','waiting'],['Support','2','open']]

export function WebsitesWorkspace() {
  return <Layout title="Websites"><section className="websitesHero card"><div><span>Owner</span><h2>Websites</h2><p>Manage websites, review drafts and publish approved changes.</p></div><button>Add Website</button></section><div className="websiteStats">{platformStats.map(card => <article className="card websiteStat" key={card[0]}><span>{card[0]}</span><strong>{card[1]}</strong><small>{card[2]}</small></article>)}</div><section className="websiteWorkspace"><aside className="card websiteFilters"><h2>Filters</h2>{filters.map((filter, index) => <button className={index === 0 ? 'active' : ''} key={filter}>{filter}</button>)}</aside><div><section className="card websiteListPanel"><div className="panelHead"><h2>Website List</h2><button>Add Website</button></div>{websites.map((site, index) => <WebsiteCard key={site.name} site={site} active={index === 0} />)}</section></div></section><section className="websiteDetailGrid"><div className="card websiteDetail"><div className="panelHead"><h2>Selected Website</h2><button onClick={() => location.href='/client/website'}>Preview</button></div><h3>TwoToneTaj</h3><p>Website content, media and publishing are managed through KSJ Digital.</p><div className="detailMetrics"><span>Domain<b>twotonetaj.com</b></span><span>Owner<b>Taj</b></span><span>Status<b>Live</b></span><span>Plan<b>Premium</b></span></div></div><div className="card websiteDetail"><div className="panelHead"><h2>Actions</h2><button onClick={() => location.href='/owner/clients'}>People</button></div><div className="ownerActionGrid"><button onClick={() => location.href='/owner/clients'}>Assign</button><button onClick={() => location.href='/owner/publish-requests'}>Review Drafts</button><button onClick={() => location.href='/owner/publish-requests'}>Publish</button><button onClick={() => location.href='/owner/support'}>Support</button></div></div></section></Layout>
}
