import { Layout } from '../../layouts/Shell.jsx'
import { twoToneTajRepo, twoToneTajPages, twoToneTajAssets, twoToneTajContentMap } from '../../services/twoToneTajSync.js'

function SyncBadge({ status }) {
  const safeStatus = status.replace(' ', '-').toLowerCase()
  return <span className={`syncBadge ${safeStatus}`}>{status}</span>
}

export function ClientWebsiteWorkspace() {
  return <Layout client title="My Website"><section className="clientSyncHero card"><div><span>Connected Repository</span><h2>TwoToneTaj</h2><p>Client access is locked to the TwoToneTaj website and prepared to sync with the live repository.</p></div><div className="repoCard"><b>{twoToneTajRepo.fullName}</b><small>Branch: {twoToneTajRepo.branch}</small><small>Live: {twoToneTajRepo.liveDomain}</small><a href={twoToneTajRepo.repoUrl}>Open Repository ↗</a></div></section><div className="clientWebsiteGrid"><section className="card syncPanel"><div className="panelHead"><h2>Editable Pages</h2><button>Scan Repo</button></div>{twoToneTajPages.map(page => <article className="syncRow" key={page.source}><div><b>{page.title}</b><small>{page.route} · {page.source}</small></div><SyncBadge status={page.status} /></article>)}</section><section className="card syncPanel"><div className="panelHead"><h2>Brand & Content</h2><button>Edit Brand</button></div><div className="brandSync"><h3>{twoToneTajContentMap.identity.brand}</h3><p>{twoToneTajContentMap.identity.tagline}</p><blockquote>{twoToneTajContentMap.identity.motto}</blockquote></div><div className="socialGrid">{Object.entries(twoToneTajContentMap.socials).map(([name, url]) => <div key={name}><b>{name}</b><small>{url}</small></div>)}</div></section></div><section className="card syncPanel"><div className="panelHead"><h2>Synced Assets</h2><button>Open Media Library</button></div><div className="assetSyncGrid">{twoToneTajAssets.map(asset => <article key={`${asset.folder}/${asset.name}`}><div>{asset.name.slice(0,2).toUpperCase()}</div><b>{asset.name}</b><small>{asset.folder}</small><p>{asset.usage}</p><SyncBadge status={asset.status} /></article>)}</div></section><section className="card syncPanel"><div className="panelHead"><h2>Publishing Flow</h2><button>Prepare Draft</button></div><div className="publishSteps"><span>1. Edit content in client portal</span><span>2. Save draft against TwoToneTaj mapping</span><span>3. Preview changes safely</span><span>4. Publish to KSJHub/TwoToneTaj</span></div></section></Layout>
}
