import { Layout } from '../../layouts/Shell.jsx'
import { twoToneTajPages, twoToneTajAssets, twoToneTajContentMap } from '../../services/twoToneTajSync.js'

const healthCards = [
  ['Website Status', 'Live', 'Your website is online and available.'],
  ['Last Updated', '2 hours ago', 'Recent homepage changes were saved.'],
  ['Pages', '6', 'Manage your site pages and content.'],
  ['Media', '6 assets', 'Images and brand files ready to use.'],
]

export function ClientWebsiteWorkspace() {
  return <Layout client title="My Website"><section className="clientSyncHero card"><div><span>Your Website</span><h2>TwoToneTaj</h2><p>Manage your website content, pages, images, branding and publishing from your KSJ Digital portal.</p></div><div className="repoCard clientSummary"><b>Website is Live</b><small>twotonetaj.ksjdigital.co.uk</small><small>Managed by KSJ Digital</small><a href="/client/editor">Edit Website</a></div></section><div className="clientHealthGrid">{healthCards.map(([label, value, help]) => <article className="card clientHealthCard" key={label}><span>{label}</span><strong>{value}</strong><small>{help}</small></article>)}</div><div className="clientWebsiteGrid"><section className="card syncPanel"><div className="panelHead"><h2>Website Pages</h2><button onClick={() => location.href='/client/editor'}>Edit Pages</button></div>{twoToneTajPages.map(page => <article className="syncRow" key={page.title}><div><b>{page.title}</b><small>{page.sections.join(' • ')}</small></div><button onClick={() => location.href='/client/editor'}>Edit</button></article>)}</section><section className="card syncPanel"><div className="panelHead"><h2>Brand & Socials</h2><button onClick={() => location.href='/client/settings'}>Manage Brand</button></div><div className="brandSync"><h3>{twoToneTajContentMap.identity.brand}</h3><p>{twoToneTajContentMap.identity.tagline}</p><blockquote>{twoToneTajContentMap.identity.motto}</blockquote></div><div className="socialGrid">{Object.entries(twoToneTajContentMap.socials).map(([name, url]) => <div key={name}><b>{name}</b><small>{url}</small></div>)}</div></section></div><section className="card syncPanel"><div className="panelHead"><h2>Media Library</h2><button onClick={() => location.href='/client/media'}>Open Media</button></div><div className="assetSyncGrid">{twoToneTajAssets.map(asset => <article key={asset.name}><div>{asset.name.slice(0,2).toUpperCase()}</div><b>{asset.name}</b><small>{asset.usage}</small><p>Ready to use on your website.</p></article>)}</div></section><section className="card syncPanel"><div className="panelHead"><h2>Publish Changes</h2><button>Request Publish</button></div><div className="publishSteps"><span>1. Update your pages</span><span>2. Preview the changes</span><span>3. Save your draft</span><span>4. Request publish</span></div></section></Layout>
}
