export const websites=[{name:'TwoToneTaj',domain:'twotonetaj.com',status:'Live',pages:12,media:842,visits:'3.2K',logo:'TAJ',plan:'Premium',seo:94,performance:98},{name:'KSJ Diamond Gaming',domain:'ksjdiamondgaming.com',status:'Coming Soon',pages:8,media:215,visits:'0',logo:'KD',plan:'Launch',seo:82,performance:91},{name:'Goliath',domain:'goliath.gg',status:'In Development',pages:6,media:191,visits:'156',logo:'G',plan:'Build',seo:77,performance:88}]
export const ownerStats=[['Total Websites','3','Active websites'],['Published Pages','24','Across all websites'],['Media Files','1,248','In your library'],['Total Visits','12.4K','Last 30 days']]
export const clientStats=[['My Websites','1','Active website'],['Total Pages','12','Published pages'],['Media Files','842','In your library'],['Visitors','3.2K','Last 30 days']]
export const bars=[42,58,36,74,63,91,80,67,86,95,72,88]
export const tickets=[['TwoToneTaj','Homepage banner change','High'],['KSJ Diamond Gaming','Launch page wording','Medium'],['Goliath','Discord widget issue','Low']]
export const pages=['Homepage','About','Community','Merch','Contact','Privacy','Terms']
export const mediaItems=['hero-banner.png','taj-avatar.webp','community-card.jpg','merch-preview.png','logo-transparent.webp','stream-overlay.png','discord-banner.jpg','thumbnail-pack.zip']
export const clients=[['TwoToneTaj','Premium','Live','1 website'],['KSJ Diamond Gaming','Launch','Preparing','1 website'],['Goliath','Build','In progress','1 website']]
