export const starterWebsites = [
  {
    id: 'twotonetaj',
    name: 'TwoToneTaj',
    domain: 'https://twotonetaj.ksjdigital.co.uk/',
    status: 'Live',
    pageCount: 7,
    mediaCount: 8,
    owner: 'Taj',
    logo: 'TAJ',
    plan: 'Premium',
    seo: 94,
    performance: 98,
    repository: 'KSJHub/TwoToneTaj',
    notes: 'Main live client website',
  },
  {
    id: 'ksjdiamondgaming',
    name: 'KSJ Diamond Gaming',
    domain: 'ksjdiamondgaming.com',
    status: 'Coming Soon',
    pageCount: 5,
    mediaCount: 3,
    owner: 'Morgan',
    logo: 'KD',
    plan: 'Launch',
    seo: 82,
    performance: 91,
    repository: 'KSJHub/KSJDiamondGaming',
    notes: 'Personal gaming identity',
  },
  {
    id: 'goliath',
    name: 'Goliath',
    domain: 'goliath.gg',
    status: 'In Development',
    pageCount: 4,
    mediaCount: 3,
    owner: 'Goliath Admin',
    logo: 'G',
    plan: 'Build',
    seo: 77,
    performance: 88,
    repository: 'KSJHub/Goliath',
    notes: 'Dashboard project',
  },
]
