export const starterWebsites = [
  {
    id: 'twotonetaj',
    name: 'TwoToneTaj',
    domain: 'https://twotonetaj.ksjdigital.co.uk/',
    status: 'Live',
    pageCount: 7,
    mediaCount: 8,
    owner: 'Taj',
    logo: 'TAJ',
    orderPrefix: 'TAJ',
    plan: 'Premium',
    seo: 94,
    performance: 98,
    repository: 'KSJHub/TwoToneTaj',
    notes: 'Main live client website',
  },
  {
    id: 'ksjdiamondgaming',
    name: 'KSJ Diamond Gaming',
    domain: 'ksjdiamondgaming.com',
    status: 'Coming Soon',
    pageCount: 5,
    mediaCount: 3,
    owner: 'Morgan',
    logo: 'KD',
    orderPrefix: 'DIA',
    plan: 'Launch',
    seo: 82,
    performance: 91,
    repository: 'KSJHub/KSJDiamondGaming',
    notes: 'Personal gaming identity',
  },
  {
    id: 'goliath',
    name: 'Goliath',
    domain: 'goliath.gg',
    status: 'In Development',
    pageCount: 4,
    mediaCount: 3,
    owner: 'Goliath Admin',
    logo: 'G',
    orderPrefix: 'GOL',
    plan: 'Build',
    seo: 77,
    performance: 88,
    repository: 'KSJHub/Goliath',
    notes: 'Dashboard project',
  },
]

export const starterClients = [
  {
    id: 'taj',
    name: 'Taj',
    email: 'taj@twotonetaj.com',
    accessCode: process.env.TWOTONETAJ_CLIENT_PASSWORD || '',
    role: 'Client',
    websiteIds: ['twotonetaj'],
    status: 'Active',
    access: 'Website editor',
    canEdit: true,
    canRequestUpdates: true,
    canManageMedia: true,
    canViewSupport: true,
  },
  {
    id: 'morgan',
    name: 'Morgan',
    email: 'ksj@ksjdigital.co.uk',
    accessCode: process.env.KSJ_OWNER_PASSWORD || '',
    role: 'Owner',
    websiteIds: ['twotonetaj', 'ksjdiamondgaming', 'goliath'],
    status: 'Active',
    access: 'Full owner access',
    canEdit: true,
    canRequestUpdates: true,
    canManageMedia: true,
    canViewSupport: true,
  },
  {
    id: 'goliath-admin',
    name: 'Goliath Admin',
    email: 'admin@goliath.gg',
    accessCode: process.env.GOLIATH_CLIENT_PASSWORD || '',
    role: 'Client',
    websiteIds: ['goliath'],
    status: 'Draft',
    access: 'Website editor',
    canEdit: true,
    canRequestUpdates: true,
    canManageMedia: true,
    canViewSupport: true,
  },
]
