export const starterSiteContent = {
  twotonetaj: {
    brand: {
      name: 'TwoToneTaj',
      tagline: 'Average Gamer • Est. 1989',
      shortTagline: 'Average gamer. Legendary vibes.',
      ownerName: 'Taj',
      communityName: 'TajSquad',
      supportCredit: 'Website by KSJ Digital',
    },
    contact: {
      supportEmail: 'support@ksjdigital.co.uk',
      businessEmail: 'media@ksjdigital.co.uk',
    },
    socials: {
      twitch: 'https://www.twitch.tv/twotonetaj',
      youtube: 'https://www.youtube.com/@twotonetaj',
      tiktok: 'https://www.tiktok.com/@twotonetaj',
      kick: 'https://kick.com/twotonetaj',
      instagram: 'https://www.instagram.com/twotonetaj',
      discord: 'https://discord.gg/WcbtQPuByd',
      linktree: 'https://linktr.ee/Twotonetaj',
      paypal: 'https://paypal.me/2tonetaj',
    },
    platforms: {
      twitchChannel: 'twotonetaj',
      youtubeChannelId: 'UC54tVexRR4IXeXpzg2Dq1UA',
    },
    engine: {
      pages: [],
      pageBlocks: {},
    },
    home: {
      heroTitle: 'TwoToneTaj',
      heroText: 'TwoToneTaj, an average gamer with a passion for games, a pure heart, good laughs, and an awesome community.',
      aboutText: 'I’ve been gaming since 1989 and I’m here for the fun, the challenge, and the community. You’ll find gameplay, chill streams, and plenty of unforgettable moments with the TajSquad.',
      merchTitle: 'Official TwoToneTaj Merch',
      merchText: 'Hoodies, creator apparel, and exclusive TajSquad merchandise are in development.',
    },
    about: {
      title: "Hey, I'm Taj",
      subtitle: 'Average gamer • Professional scoreboard victim.',
      intro: 'Welcome to TwoToneTaj. A gaming community built on laughs, good people, and unforgettable moments.',
      quote: 'Gaming was never about the scoreboard for me, it was always about the people.',
      sections: [
        { title: '🎮 Where It Started', text: 'I came into FPS games late and, honestly, I was terrible. But I kept coming back because I loved the people, not the stats.' },
        { title: '🌧️ Life Got Heavy', text: 'During difficult chapters, gaming became a way to switch off, connect with others, and find a bit of light when I needed it most.' },
        { title: '🎥 Streaming Began', text: 'At first, nobody watched. Most streams felt like I was talking to myself, but I kept showing up.' },
        { title: '🔁 Balance Changed Everything', text: 'Eventually, I realised gaming could not solve everything. I needed balance.' },
        { title: '💥 The Moment Everything Changed', text: 'One day, XHubbaxx dropped into stream, helped me improve my setup, and what began as a quick test became a 12-hour stream.' },
        { title: 'Welcome to TajSquad', text: 'TwoToneTaj is a place to relax, laugh, unwind, and be yourself. No pressure. No drama. Just good people having a good time.' },
      ],
    },
    contentPage: {
      eyebrow: 'Videos • Streams • Clips',
      title: 'Watch The Chaos',
      intro: 'The home of TwoToneTaj content — gameplay, streams, community moments, shorts and the clips that prove the scoreboard was never the most important part.',
      latestTitle: 'Recent YouTube Uploads',
      latestText: 'Fresh videos and shorts pulled from the official TwoToneTaj YouTube channel.',
      platformTitle: 'Choose Your Platform',
      footerTitle: 'It’s All About The 💩 And Giggles, Folks.',
      footerText: 'No fake perfection. No pretending every match is a masterclass. Just gaming, community and the moments worth sharing.',
    },
    communityPage: {
      eyebrow: 'Official Discord Community',
      title: 'TajSquad Community',
      intro: 'The home of TwoToneTaj — good games, good laughs, stream alerts, clips, voice hangouts, community nights and the people who make the whole thing worth building.',
      dashboardTitle: 'The Discord Is The Heart Of TajSquad',
      dashboardText: 'The website shows public Discord information and will continue to grow with community events, announcements and updates.',
      areasTitle: 'Everything TajSquad Needs',
      valuesTitle: 'Protect The Vibe',
      valuesText: 'TajSquad is built around laughs, respect, support and proper community energy.',
    },
    contactPage: {
      eyebrow: 'Official Contact',
      title: 'Let’s Talk',
      intro: 'For collaborations, media opportunities, community questions or a quick hello, use the official contact routes below.',
      linksTitle: 'Links & Support',
      enquiriesTitle: 'Enquiries Welcome',
      enquiriesText: 'Relevant opportunities are always considered. A clear introduction, useful details and realistic timelines make every enquiry easier to review.',
      thanksTitle: 'Thank You For Being Part Of The Community',
      thanksText: 'Every message, share, laugh and bit of support helps the community grow and keeps the content moving.',
    },
    privacy: {
      eyebrow: 'Legal',
      title: 'Privacy Policy',
      intro: 'This Privacy Policy explains how this website handles basic information when you use it.',
      sections: [
        { title: '1. Who we are', text: 'This website is operated for TwoToneTaj and supported by KSJ Digital.' },
        { title: '2. Information we may collect', text: 'This website may collect limited technical and usage information when you visit pages or interact with embedded content.' },
        { title: '3. Contact emails', text: 'If you contact us by email, we may receive your email address, message and any information you choose to include.' },
        { title: '4. Third-party services', text: 'This website may link to or display content from third-party platforms. Those platforms have their own privacy policies.' },
        { title: '5. Cookies and browser storage', text: 'The site may use basic browser storage for small features and preferences.' },
        { title: '6. How information is used', text: 'Information is used to operate the website, respond to enquiries and improve the user experience.' },
        { title: '7. Data sharing', text: 'We do not sell personal information. Information is only shared where required to operate or protect the website.' },
        { title: '8. Your rights', text: 'You may contact us to request access, correction or deletion of personal information you have provided, where applicable.' },
        { title: '9. Changes to this policy', text: 'This policy may be updated as the website develops or new features are added.' },
      ],
      updated: 'Last updated: June 2026',
    },
    terms: {
      eyebrow: 'Legal',
      title: 'Terms of Use',
      intro: 'These Terms of Use explain the rules and expectations for using this website.',
      sections: [
        { title: '1. Use of this website', text: 'Use this website responsibly and only for lawful purposes.' },
        { title: '2. Website content', text: 'Content is provided for general information, entertainment, community updates and creator-related purposes.' },
        { title: '3. Development notice', text: 'The website may change as pages, features, layouts and content are improved.' },
        { title: '4. External links', text: 'We are not responsible for the content, policies or actions of third-party services linked from this website.' },
        { title: '5. Intellectual property', text: 'Names, branding, graphics and website content must not be copied or redistributed without permission.' },
        { title: '6. Community behaviour', text: 'Users are expected to behave respectfully when interacting with related content and community services.' },
        { title: '7. No guarantees', text: 'The website is provided as-is and may not always be uninterrupted, error-free or fully up to date.' },
        { title: '8. Support', text: 'For website support or technical questions, contact KSJ Digital.' },
        { title: '9. Changes to these terms', text: 'These terms may be updated as the website develops or new features are added.' },
      ],
      updated: 'Last updated: June 2026',
    },
  },
}
