const websites=[{name:'TwoToneTaj',domain:'twotonetaj.com',status:'Live',pages:12,media:842,visits:'3.2K',logo:'TAJ',plan:'Premium',seo:94,performance:98},{name:'KSJ Diamond Gaming',domain:'ksjdiamondgaming.com',status:'Coming Soon',pages:8,media:215,visits:'0',logo:'KD',plan:'Launch',seo:82,performance:91},{name:'Goliath',domain:'goliath.gg',status:'In Development',pages:6,media:191,visits:'156',logo:'G',plan:'Build',seo:77,performance:88}]
const ownerStats=[['Total Websites','3','Active websites'],['Published Pages','24','Across all websites'],['Media Files','1,248','In your library'],['Total Visits','12.4K','Last 30 days']]
const clientStats=[['My Websites','1','Active website'],['Total Pages','12','Published pages'],['Media Files','842','In your library'],['Visitors','3.2K','Last 30 days']]
const bars=[42,58,36,74,63,91,80,67,86,95,72,88]
const tickets=[['TwoToneTaj','Homepage banner change','High'],['KSJ Diamond Gaming','Launch page wording','Medium'],['Goliath','Discord widget issue','Low']]
const pages=['Homepage','About','Community','Merch','Contact','Privacy','Terms']
const media=['hero-banner.png','taj-avatar.webp','community-card.jpg','merch-preview.png','logo-transparent.webp','stream-overlay.png','discord-banner.jpg','thumbnail-pack.zip']
function Logo(){return <div className="logo"><div className="logoMark">K</div><b>KSJ DIGITAL</b></div>}
function route(){return location.pathname.replace(/\/$/,'')||'/'}function go(path){location.href=path}
function Sidebar({client=false}){const items=client?[['/client','Dashboard'],['/client/website','My Website'],['/client/editor','Pages / Editor'],['/client/media','Media Library'],['/client/analytics','Analytics'],['/client/support','Support'],['/client/settings','Settings']]:[['/owner','Dashboard'],['/owner/websites','Websites'],['/owner/clients','Clients'],['/owner/analytics','Analytics'],['/owner/support','Support'],['/owner/settings','Settings']];const current=route();return <aside className="sidebar"><Logo/><nav>{items.map(([path,label])=><button className={current===path?'active':''} key={path} onClick={()=>go(path)}><span>{label}</span></button>)}</nav><div className="supportBox"><b>Need Help?</b><p>Support, updates and client requests in one place.</p><button onClick={()=>go(client?'/client/support':'/owner/support')}>Contact Support</button></div></aside>}
function Header({client=false,title}){return <header className="header"><div><span>{client?'Client Portal':'Owner Platform'}</span><h1>{title||(client?'Taj (TwoToneTaj)':'Morgan')} 👋</h1><p>{client?'Manage your website, content and support from one dashboard.':'Manage every KSJ Digital website, client and service from one dashboard.'}</p></div><div className="tools"><div className="search">Search everything...</div><button>🔔 3</button><button>KSJ DIGITAL <span className="miniAvatar">{client?'T':'M'}</span></button></div></header>}
function Stat({item}){return <div className="card stat"><div><span>{item[0]}</span><strong>{item[1]}</strong><small>{item[2]}</small></div><i/></div>}
function WebsiteCard({site,active=false}){return <article className={active?'website activeSite':'website'}><div className="thumb">{site.logo}</div><div><h3>{site.name} <em>{site.status}</em></h3><p>{site.domain} · {site.plan}</p><div className="siteStats"><b>{site.pages}<small>Pages</small></b><b>{site.media}<small>Media</small></b><b>{site.visits}<small>Visits</small></b><b>{site.seo}%<small>SEO</small></b><b>{site.performance}%<small>Speed</small></b></div></div><button>Manage</button></article>}
function Preview(){return <section className="card preview"><div className="panelHead"><h2>Website Preview</h2><div><button>Desktop</button><button>Tablet</button><button>Mobile</button></div></div><div className="sitePreview"><div className="mockNav"><b>TAJ</b><span>HOME</span><span>ABOUT</span><span>COMMUNITY</span><span>MERCH</span><span>CONTACT</span></div><div className="mockHero"><p>WELCOME TO</p><h2>TWOTONE<span>TAJ</span></h2><h4>It&apos;s all about the 💩 and giggles, folks.</h4><button>JOIN THE SQUAD</button></div></div><footer><span></span> Live <button>Visit Live Site ↗</button></footer></section>}
function AnalyticsPanel(){return <section className="card analytics"><div className="panelHead"><h2>Analytics Snapshot</h2><a>Last 30 days</a></div><div className="chart">{bars.map((b,i)=><span key={i} style={{height:`${b}%`}}></span>)}</div><div className="miniStats"><b>+18.6%<small>Traffic</small></b><b>72%<small>Desktop</small></b><b>24%<small>Mobile</small></b><b>4%<small>Tablet</small></b></div></section>}
function ActivityPanel(){return <section className="card activity"><div className="panelHead"><h2>Recent Activity</h2><a>View All</a></div>{['Homepage updated','New banner uploaded','About page published','Support ticket replied','Analytics report ready'].map((x,i)=><p key={x}><i></i><b>{x}</b><small>{i+1}h ago</small></p>)}</section>}
function TicketPanel(){return <section className="card tickets"><div className="panelHead"><h2>Open Support</h2><a>View tickets</a></div>{tickets.map(([client,subject,priority])=><p key={subject}><b>{subject}<small>{client}</small></b><em>{priority}</em></p>)}</section>}
function QuickActions({client=false}){const actions=client?['Edit Website','Add Page','Upload Media','Open Support','View Analytics','Update Settings']:['Create Website','Add Client','Review Tickets','Publish Changes','Open Analytics','Platform Settings'];return <section className="card quick"><h2>Quick Actions</h2><div>{actions.map(x=><button key={x}>{x}</button>)}</div></section>}
function StatusPanel(){return <section className="card status"><h2>System Status</h2><h3>✓ All Systems Operational</h3>{['Website Hosting','Database','CDN','Backups'].map(x=><p key={x}><span>✓</span>{x}<small>Operational</small></p>)}</section>}
function Dashboard({client=false}){return <div className="shell"><Sidebar client={client}/><main><Header client={client}/><div className="stats">{(client?clientStats:ownerStats).map(item=><Stat key={item[0]} item={item}/>)}</div><div className="singleGrid"><section className="card websites"><div className="panelHead"><h2>{client?'My Website':'Your Websites'}</h2><button>{client?'Edit Website':'Create New Website'}</button></div>{(client?[websites[0]]:websites).map((site,i)=><WebsiteCard key={site.name} site={site} active={i===0}/>)}</section><Preview/></div><div className="bottom four"><AnalyticsPanel/><ActivityPanel/><TicketPanel/><StatusPanel/></div><QuickActions client={client}/></main></div>}
function EditorWorkspace({client=false}){return <div className="shell"><Sidebar client={client}/><main><Header client={client} title="Pages / Editor"/><section className="editorGrid"><div className="card pageList"><div className="panelHead"><h2>Pages</h2><button>Add Page</button></div>{pages.map((p,i)=><button className={i===0?'selected':''} key={p}>{p}<small>{i<5?'Published':'Draft'}</small></button>)}</div><div className="card editorPanel"><div className="panelHead"><h2>Homepage Editor</h2><button>Save Draft</button></div>{['Hero Title','Subtitle','Primary Button','SEO Description'].map((field,i)=><label key={field}>{field}<input defaultValue={i===0?'TwoToneTaj':i===1?'Gaming community, streams and merch':i===2?'Join The Squad':'Average gamer. Community builder.'}/></label>)}<div className="editorActions"><button>Preview</button><button>Publish Changes</button></div></div><Preview/></section></main></div>}
function MediaWorkspace({client=false}){return <div className="shell"><Sidebar client={client}/><main><Header client={client} title="Media Library"/><section className="card uploadZone"><h2>Drop files here</h2><p>Upload images, banners, overlays, icons and brand assets.</p><button>Upload Media</button></section><div className="mediaGrid">{media.map((m,i)=><div className="card mediaItem" key={m}><div>{m.split('.')[0].slice(0,2).toUpperCase()}</div><b>{m}</b><small>{i%2?'Used on Homepage':'Brand Asset'}</small></div>)}</div></main></div>}
function SupportWorkspace({client=false}){return <div className="shell"><Sidebar client={client}/><main><Header client={client} title="Support"/><div className="supportGrid"><TicketPanel/><section className="card conversation"><h2>Ticket Conversation</h2><p><b>Client:</b> Can we update the homepage banner before launch?</p><p><b>KSJ:</b> Yes, upload the replacement image and we will prepare the draft.</p><textarea placeholder="Write reply..."></textarea><button>Send Reply</button></section><StatusPanel/></div></main></div>}
function SettingsWorkspace({client=false}){return <div className="shell"><Sidebar client={client}/><main><Header client={client} title="Settings"/><div className="settingsGrid">{['Profile','Security','Notifications','Brand Settings','Billing','Permissions'].map((s,i)=><section className="card settingCard" key={s}><span>0{i+1}</span><h2>{s}</h2><p>Configure {s.toLowerCase()} for this KSJ Digital workspace.</p><button>Open Settings</button></section>)}</div></main></div>}
function ModulePage({client=false,type='websites'}){if(type==='editor')return <EditorWorkspace client={client}/>;if(type==='media')return <MediaWorkspace client={client}/>;if(type==='support')return <SupportWorkspace client={client}/>;if(type==='settings')return <SettingsWorkspace client={client}/>;const list={websites:['Website overview','Domain and SSL','Publishing workflow','SEO and speed scores'],clients:['Client profile','Assigned websites','Access permissions','Account notes'],analytics:['Traffic overview','Visitor devices','Top pages','Performance trends']}[type]||['Overview','Workflow','Insights','Actions'];const title=type[0].toUpperCase()+type.slice(1).replace('-',' ');return <div className="shell"><Sidebar client={client}/><main><Header client={client} title={title}/><section className="moduleHero card"><div><span>{client?'Client module':'Owner module'}</span><h2>{title}</h2><p>This workspace is ready for permissions, mock data and real actions.</p></div><button>Primary Action</button></section><div className="moduleGrid">{list.map((x,i)=><div className="card moduleCard" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Premium dark SaaS panel prepared for live data, editing, filtering and workflow actions.</p><div className="progress"><i style={{width:`${70+i*7}%`}}></i></div></div>)}</div><div className="bottom"><AnalyticsPanel/><TicketPanel/><StatusPanel/></div></main></div>}
function Login(){return <div className="login"><div className="card loginCard"><Logo/><h1>KSJ Digital Ecosystem</h1><p>The central hub for managing websites, content, media, analytics and support.</p><a href="/owner">Open Owner Platform</a><a href="/client">Open Client Portal</a></div></div>}
export default function App(){const p=route();if(p==='/owner')return <Dashboard/>;if(p==='/client')return <Dashboard client/>;if(p.startsWith('/owner/'))return <ModulePage type={p.split('/')[2]}/>;if(p.startsWith('/client/'))return <ModulePage client type={p.split('/')[2]==='website'?'websites':p.split('/')[2]}/>;return <Login/>}
