import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './styles/publishing.css'
import './styles/editor.css'
import './styles/media.css'
import './styles/analytics.css'
import './styles/support.css'
import './styles/settings.css'
import './styles/websites.css'
import './styles/auth.css'
import './styles/consistency.css'
createRoot(document.getElementById('root')).render(<App />)
