import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './styles/publishing.css'
import './styles/editor.css'
import './styles/media.css'
import './styles/support.css'
import './styles/settings.css'
import './styles/websites.css'
import './styles/auth.css'
import './styles/permissions.css'
import './styles/content-model.css'
import './styles/publish-review.css'
import './styles/website-manager.css'
import './styles/accounts.css'
import './styles/branding.css'
import './styles/brand-manager.css'
import './styles/pipeline.css'
import './styles/website-actions.css'
import './styles/page-builder.css'
import './styles/site-engine.css'
import './styles/consistency.css'

createRoot(document.getElementById('root')).render(<App />)
