import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'
import './styles/public-site.css'
import './styles/client-portal.css'
import './styles/publishing.css'
import './styles/editor.css'
import './styles/media.css'
import './styles/support.css'
import './styles/settings.css'
import './styles/websites.css'
import './styles/auth.css'
import './styles/permissions.css'
import './styles/content-model.css'
import './styles/publish-review.css'
import './styles/approval-review-v2.css'
import './styles/version-history.css'
import './styles/approval-queue-cleanup.css'
import './styles/site-settings.css'
import './styles/page-seo.css'
import './styles/commerce-v2.css'
import './styles/checkout-test.css'
import './styles/website-manager.css'
import './styles/accounts.css'
import './styles/branding.css'
import './styles/brand-manager.css'
import './styles/pipeline.css'
import './styles/website-actions.css'
import './styles/page-builder.css'
import './styles/visual-editor.css'
import './styles/real-site-editor.css'
import './styles/visual-merch.css'
import './styles/visual-branding.css'
import './styles/site-engine.css'
import './styles/media-library.css'
import './styles/form-builder.css'
import './styles/operations.css'
import './styles/release-centre.css'
import './styles/consistency.css'

createRoot(document.getElementById('root')).render(<App />)
