import { getAccountFromPath } from '../services/auth.js'
import { PermissionBanner } from '../components/PermissionBanner.jsx'

function route(){return location.pathname.replace(/\/$/,'')||'/'}
function go(path){location.href=path}
export function Logo(){return <div className="logo"><div className="logoMark">K</div><b>KSJ DIGITAL</b></div>}
export function Sidebar({client=false}){const items=client?[['/client','Dashboard'],['/client/website','My Website'],['/client/editor','Pages / Editor'],['/client/media','Media Library'],['/client/analytics','Analytics'],['/client/support','Support'],['/client/publish','Publish Requests'],['/client/settings','Settings']]:[['/owner','Dashboard'],['/owner/websites','Websites'],['/owner/clients','Clients'],['/owner/analytics','Analytics'],['/owner/support','Support'],['/owner/publish-requests','Publish Requests'],['/owner/deployments','Deployments'],['/owner/integrations','Integrations'],['/owner/settings','Settings']];const current=route();return <aside className="sidebar"><Logo/><nav>{items.map(([path,label])=><button className={current===path?'active':''} key={path} onClick={()=>go(path)}><span>{label}</span></button>)}</nav><div className="supportBox"><b>Need Help?</b><p>Support, updates and client requests in one place.</p><button onClick={()=>go(client?'/client/support':'/owner/support')}>Contact Support</button></div></aside>}
export function Header({client=false,title,account}){const activeAccount=account||getAccountFromPath();return <header className="header"><div><span>{client?'Client Portal':'Owner Platform'}</span><h1>{title||activeAccount.name} 👋</h1><p>{client?'Manage your assigned website, content and support from one dashboard.':'Manage KSJ Digital websites, clients, publishing and access from one dashboard.'}</p></div><div className="tools"><div className="search">Search everything...</div><button>🔔 3</button><button>{activeAccount.label}<span className="miniAvatar">{activeAccount.name[0]}</span></button></div></header>}
export function Layout({client=false,title,children}){const account=getAccountFromPath();return <div className="shell"><Sidebar client={client}/><main><Header client={client} title={title} account={account}/><PermissionBanner client={client} account={account}/>{children}</main></div>}
